version: '3.8'

services:
  # Django application
  web:
    build: .
    container_name: dhaharan_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env

  # Nginx (optional - untuk production)
  # nginx:
  #   image: nginx:alpine
  #   container_name: dhaharan_nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - static_volume:/app/staticfiles
  #     - media_volume:/app/media
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web

volumes:
  static_volume:
  media_volume:
